openapi: 3.0.3
info:
  title: tasks
  version: 1.1.0
servers:
  - url: http://localhost:8000
paths:
  /tasks:
    get:
      responses:
        200:
          description: Retourne une liste de Task [].
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/tasks"
              example:
                - id: 1
                  title: Faire les courses
                  completed: false
                - id: 2
                  title: Apprendre OpenAPI
                  completed: true

components:
  schemas:
    tasks:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: Faire les courses
        completed:
          type: boolean
          example: false
