openapi: 3.0.3
info:
  title: Tasks
  version: 1.1.0
servers:
  - url: http://localhost:8000
paths:
  /tasks:
    get:
      responses:
        200:
          description: Retourne une liste de Task [].
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
              example:
                - id: 1
                  title: Faire les courses
                  completed: false
                - id: 2
                  title: Apprendre OpenAPI
                  completed: true
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/newTask"
            example:
              - title: newTask 1
                completed: false
              - title: test 2
                completed: true
      responses:
        201:
          description: Retourne la liste nouvelle créée
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
              example:
                - id: 1
                  title: newTask 1
                  completed: false
                - id: 2
                  title: test 2
                  completed: false
    delete:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/idTask"
      responses:
        200:
          description: Supprimer une liste de tache
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
                example:
                  id: 1
                  title: Faire les courses
                  completed: false

  /tasks/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: ID de la tache a recuperer
          required: true
          schema:
            $ref: "#/components/schemas/idTask"
      responses:
        200:
          description: tache trouvee
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
              example:
                id: 1
                title: Faire les courses
                completed: false
        404:
          description: tache non trouvee
          content:
            application/json:
              example:
                error: Task not found
    delete:
      parameters:
        - name: id
          in: path
          description: ID de la tache a suprimer
          required: true
          schema:
            items:
              $ref: "#/components/schemas/idTask"
      responses:
        200:
          description: tache suprimer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
              example:
                id: 1
                title: Faire les courses
                completed: false
        404:
          description: tache non trouvee
          content:
            application/json:
              example:
                error: Task not found

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: Faire les courses
        completed:
          type: boolean
          example: false
    newTask:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: Nouvelle tache
        completed:
          type: boolean
          example: false
    idTask:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
